[book]
authors = ["vismate"]
language = "hu"
multilingual = false
src = "src"
title = "4. félévi jegyzetek"

[output.katex]

[output.html]
no-section-label = true
default-theme = "ayu"
additional-css = ["src/image_style.css"]
git-repository-url = "https://github.com/vismate/jegyzetek-4"
git-repository-icon = "fa-github"

[preprocessor.katex]
renderers = ["html"]